# import_pentacam build system
#
# Usage:
#   ./configure           One-time setup (downloads ONNX Runtime, detects CUDA)
#   make                  Build release binary
#   make dist             Build + assemble distributable folder
#   make dist-tar         Build + create .tar.gz archive
#   make deb              Build + create .deb package
#   make install          Build + install to PREFIX (default: ~/.local)
#   make clean            Remove build artifacts and dist folder
#
# See INSTALL for details.

# Include configuration (generated by ./configure)
-include config.mk

# Defaults if config.mk doesn't exist (fallback for manual builds)
ORT_DIR        ?= /tmp/onnxruntime-linux-x64-gpu-1.20.1
CUDA_PROVIDER  ?= 1
PREFIX         ?= $(HOME)/.local

DIST_DIR   := dist/import_pentacam
VERSION    := $(shell grep '^version' import_pentacam/Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')
DEB_PKG    := import-pentacam_$(VERSION)_amd64

# ORT build environment
export ORT_LIB_LOCATION := $(ORT_DIR)/lib
export ORT_PREFER_DYNAMIC_LINK := 1

.PHONY: build dist dist-tar deb install clean check-config

check-config:
	@if [ ! -f config.mk ]; then \
		echo ""; \
		echo "  config.mk not found. Run ./configure first:"; \
		echo ""; \
		echo "    ./configure"; \
		echo "    make"; \
		echo ""; \
		echo "  Or for CPU-only (no CUDA): ./configure --cpu-only"; \
		echo ""; \
		exit 1; \
	fi

build: check-config
	cargo build --release

dist: build
	@echo "Assembling distribution in $(DIST_DIR) ..."
	@rm -rf $(DIST_DIR)
	@mkdir -p $(DIST_DIR)/models
	@# Binary
	cp target/release/import_pentacam $(DIST_DIR)/
	@# ORT core library
	cp $(ORT_DIR)/lib/libonnxruntime.so.1.20.1 $(DIST_DIR)/
	ln -sf libonnxruntime.so.1.20.1 $(DIST_DIR)/libonnxruntime.so.1
	ln -sf libonnxruntime.so.1 $(DIST_DIR)/libonnxruntime.so
ifeq ($(CUDA_PROVIDER),1)
	@# GPU providers (optional — binary falls back to CPU if missing)
	cp $(ORT_DIR)/lib/libonnxruntime_providers_cuda.so $(DIST_DIR)/
	cp $(ORT_DIR)/lib/libonnxruntime_providers_shared.so $(DIST_DIR)/
endif
	@# OCR models
	cp models/pp-ocrv5_server_det.onnx $(DIST_DIR)/models/
	cp models/en_pp-ocrv5_mobile_rec.onnx $(DIST_DIR)/models/
	cp models/en_ppocrv5_dict.txt $(DIST_DIR)/models/
	@echo ""
	@echo "Distribution ready: $(DIST_DIR)/"
	@echo "  Binary:  $(DIST_DIR)/import_pentacam"
	@echo "  Models:  $(DIST_DIR)/models/"
	@echo "  ORT:     $(DIST_DIR)/libonnxruntime.so.1.20.1"
ifeq ($(CUDA_PROVIDER),1)
	@echo "  GPU:     $(DIST_DIR)/libonnxruntime_providers_cuda.so"
endif
	@echo ""
	@echo "Test:  cd $(DIST_DIR) && ./import_pentacam --help"

dist-tar: dist
	@echo "Creating archive ..."
	cd dist && tar czf import_pentacam-$(VERSION)-linux-x64.tar.gz import_pentacam/
	@echo "Archive: dist/import_pentacam-$(VERSION)-linux-x64.tar.gz"

deb: dist
	@echo "Building .deb package ..."
	@rm -rf dist/$(DEB_PKG)
	@# Directory structure
	@mkdir -p dist/$(DEB_PKG)/usr/lib/import_pentacam/models
	@mkdir -p dist/$(DEB_PKG)/usr/bin
	@mkdir -p dist/$(DEB_PKG)/DEBIAN
	@# Copy files
	cp $(DIST_DIR)/import_pentacam dist/$(DEB_PKG)/usr/lib/import_pentacam/
	cp $(DIST_DIR)/libonnxruntime.so.1.20.1 dist/$(DEB_PKG)/usr/lib/import_pentacam/
	ln -sf libonnxruntime.so.1.20.1 dist/$(DEB_PKG)/usr/lib/import_pentacam/libonnxruntime.so.1
	ln -sf libonnxruntime.so.1 dist/$(DEB_PKG)/usr/lib/import_pentacam/libonnxruntime.so
ifeq ($(CUDA_PROVIDER),1)
	cp $(DIST_DIR)/libonnxruntime_providers_cuda.so dist/$(DEB_PKG)/usr/lib/import_pentacam/
	cp $(DIST_DIR)/libonnxruntime_providers_shared.so dist/$(DEB_PKG)/usr/lib/import_pentacam/
endif
	cp -r $(DIST_DIR)/models/* dist/$(DEB_PKG)/usr/lib/import_pentacam/models/
	@# Wrapper script
	@echo '#!/bin/sh' > dist/$(DEB_PKG)/usr/bin/import_pentacam
	@echo 'exec /usr/lib/import_pentacam/import_pentacam "$$@"' >> dist/$(DEB_PKG)/usr/bin/import_pentacam
	@chmod +x dist/$(DEB_PKG)/usr/bin/import_pentacam
	@# Control file
	@INSTALLED_SIZE=$$(du -sk dist/$(DEB_PKG)/usr | cut -f1) && \
	echo "Package: import-pentacam" > dist/$(DEB_PKG)/DEBIAN/control && \
	echo "Version: $(VERSION)" >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo "Section: science" >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo "Priority: optional" >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo "Architecture: amd64" >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo "Installed-Size: $$INSTALLED_SIZE" >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo "Maintainer: Tobias Elze <tobias.elze@gmail.com>" >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo "Description: Extract clinical measurements from Pentacam DICOM/PDF/image files" >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo " Extracts keratometry, pachymetry, and other clinical measurements from" >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo " Pentacam ophthalmic imaging files. Supports DICOM Structured Reports," >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo " proprietary SPR binary data, and OCR-based extraction from printout pages." >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo " Outputs CSV files compatible with import_spectralis conventions." >> dist/$(DEB_PKG)/DEBIAN/control && \
	echo "Suggests: nvidia-driver-535" >> dist/$(DEB_PKG)/DEBIAN/control
	@# Build .deb
	dpkg-deb --build --root-owner-group dist/$(DEB_PKG)
	@echo ""
	@echo "Package: dist/$(DEB_PKG).deb"
	@echo "Install: sudo dpkg -i dist/$(DEB_PKG).deb"

install: dist
	@echo "Installing to $(PREFIX) ..."
	@mkdir -p $(PREFIX)/lib/import_pentacam/models
	@mkdir -p $(PREFIX)/bin
	cp $(DIST_DIR)/import_pentacam $(PREFIX)/lib/import_pentacam/
	cp $(DIST_DIR)/libonnxruntime* $(PREFIX)/lib/import_pentacam/
	cp -r $(DIST_DIR)/models/* $(PREFIX)/lib/import_pentacam/models/
	@# Create wrapper script that runs from the lib directory
	@echo '#!/bin/sh' > $(PREFIX)/bin/import_pentacam
	@echo 'exec "$(PREFIX)/lib/import_pentacam/import_pentacam" "$$@"' >> $(PREFIX)/bin/import_pentacam
	@chmod +x $(PREFIX)/bin/import_pentacam
	@echo ""
	@echo "Installed to $(PREFIX)/lib/import_pentacam/"
	@echo "Wrapper:  $(PREFIX)/bin/import_pentacam"
	@echo ""
	@echo "Make sure $(PREFIX)/bin is in your PATH."

clean:
	cargo clean
	rm -rf dist/
