# import_pentacam build system
#
# Usage:
#   ./configure           One-time setup (downloads ONNX Runtime, detects CUDA)
#   make                  Build release binary
#   make dist             Build + assemble distributable folder
#   make dist-tar         Build + create .tar.gz archive
#   make install          Build + install to PREFIX (default: ~/.local)
#   make clean            Remove build artifacts and dist folder
#
# See INSTALL for details.

# Include configuration (generated by ./configure)
-include config.mk

# Defaults if config.mk doesn't exist (fallback for manual builds)
ORT_DIR        ?= /tmp/onnxruntime-linux-x64-gpu-1.20.1
CUDA_PROVIDER  ?= 1
PREFIX         ?= $(HOME)/.local

DIST_DIR   := dist/import_pentacam
VERSION    := $(shell grep '^version' import_pentacam/Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')

# ORT build environment
export ORT_LIB_LOCATION := $(ORT_DIR)/lib
export ORT_PREFER_DYNAMIC_LINK := 1

.PHONY: build dist dist-tar install clean check-config

check-config:
	@if [ ! -f config.mk ]; then \
		echo ""; \
		echo "  config.mk not found. Run ./configure first:"; \
		echo ""; \
		echo "    ./configure"; \
		echo "    make"; \
		echo ""; \
		echo "  Or for CPU-only (no CUDA): ./configure --cpu-only"; \
		echo ""; \
		exit 1; \
	fi

build: check-config
	cargo build --release

dist: build
	@echo "Assembling distribution in $(DIST_DIR) ..."
	@rm -rf $(DIST_DIR)
	@mkdir -p $(DIST_DIR)/models
	@# Binary
	cp target/release/import_pentacam $(DIST_DIR)/
	@# ORT core library
	cp $(ORT_DIR)/lib/libonnxruntime.so.1.20.1 $(DIST_DIR)/
	ln -sf libonnxruntime.so.1.20.1 $(DIST_DIR)/libonnxruntime.so.1
	ln -sf libonnxruntime.so.1 $(DIST_DIR)/libonnxruntime.so
ifeq ($(CUDA_PROVIDER),1)
	@# GPU providers (optional — binary falls back to CPU if missing)
	cp $(ORT_DIR)/lib/libonnxruntime_providers_cuda.so $(DIST_DIR)/
	cp $(ORT_DIR)/lib/libonnxruntime_providers_shared.so $(DIST_DIR)/
endif
	@# OCR models
	cp models/pp-ocrv5_server_det.onnx $(DIST_DIR)/models/
	cp models/en_pp-ocrv5_mobile_rec.onnx $(DIST_DIR)/models/
	cp models/en_ppocrv5_dict.txt $(DIST_DIR)/models/
	@echo ""
	@echo "Distribution ready: $(DIST_DIR)/"
	@echo "  Binary:  $(DIST_DIR)/import_pentacam"
	@echo "  Models:  $(DIST_DIR)/models/"
	@echo "  ORT:     $(DIST_DIR)/libonnxruntime.so.1.20.1"
ifeq ($(CUDA_PROVIDER),1)
	@echo "  GPU:     $(DIST_DIR)/libonnxruntime_providers_cuda.so"
endif
	@echo ""
	@echo "Test:  cd $(DIST_DIR) && ./import_pentacam --help"

dist-tar: dist
	@echo "Creating archive ..."
	cd dist && tar czf import_pentacam-$(VERSION)-linux-x64.tar.gz import_pentacam/
	@echo "Archive: dist/import_pentacam-$(VERSION)-linux-x64.tar.gz"

install: dist
	@echo "Installing to $(PREFIX) ..."
	@mkdir -p $(PREFIX)/lib/import_pentacam/models
	@mkdir -p $(PREFIX)/bin
	cp $(DIST_DIR)/import_pentacam $(PREFIX)/lib/import_pentacam/
	cp $(DIST_DIR)/libonnxruntime* $(PREFIX)/lib/import_pentacam/
	cp -r $(DIST_DIR)/models/* $(PREFIX)/lib/import_pentacam/models/
	@# Create wrapper script that runs from the lib directory
	@echo '#!/bin/sh' > $(PREFIX)/bin/import_pentacam
	@echo 'exec "$(PREFIX)/lib/import_pentacam/import_pentacam" "$$@"' >> $(PREFIX)/bin/import_pentacam
	@chmod +x $(PREFIX)/bin/import_pentacam
	@echo ""
	@echo "Installed to $(PREFIX)/lib/import_pentacam/"
	@echo "Wrapper:  $(PREFIX)/bin/import_pentacam"
	@echo ""
	@echo "Make sure $(PREFIX)/bin is in your PATH."

clean:
	cargo clean
	rm -rf dist/
